[package]
name = "rust_nhpylm"
version = "0.1.0"
authors = ["Xiang Ji <hi@xiangji.me>"]

[lib]
name = "rust_nhpylm"
path = "src/lib.rs"
doc = true

[dependencies]
rand = "0.6.5"
either = "1.5.1"
statrs = "0.10.0"
ndarray = "0.12.1"
